### ISSUE TITLE
Planning v2

### ISSUE THREAD

**Issue by wadackel** [scaffdog/scaffdog#333]
## Breaking Changes

- [x] Drop support for Node.js 12 #379

## Template

- [x] If Statement or Expression #373
- [x] Variable Statement / Expression #373
- [x] Support array values #397
- [x] Support helper functions for array values #400
- [x] Skip file generation #401

## Misc

- [x] Document site #418
- [x] Playground
- [x] Migration guide ([see](https://github.com/scaffdog/scaffdog/blob/canary/MIGRATION.md#to-v2-from-v1))

## After v2 (coming soon)

- [ ] Conditional prompt
- [ ] Support for flags to answer questions (Additional features will be added after v2 release)

---

We are considering these plans :dog:
